name: nettverk
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.1
  provider: ^6.1.2
  go_router: ^14.3.0
  package_info_plus: ^8.1.0
  webfeed_revised: ^0.8.0
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:
  color: "#FFF7FF" # background color of your splash screen (use hex format)
  image: assets/splash.png # your splash screen image
  android: true
  ios: true
  web: false
